app/controllers/image.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.models import db, Tag, Image, Category
import os
from werkzeug.utils import secure_filename
from PIL import Image as Picture
import pymysql
import math



image = Blueprint('image', __name__, url_prefix='/')


@image.route('/', methods=['GET', 'POST'])
def index():
    return redirect(url_for('image.importImg'))

@image.route('/import', methods=['GET', 'POST'])
def importImg():
    message_error = ""
    
    # recupére tout les tags
    tags = Tag.query.all()
    images = Image.query.all()

    if request.method == 'POST':
        typeImg = request.form.get('typeImg')
        isProduct = request.form.get('isProduct')
        isHuman = request.form.get('isHuman')
        isInstitutional = request.form.get('isInstitutional')
        credit = request.form.get('credit')
        rightOfUse = request.form.get('rightOfUse')
        copyrightImg = request.form.get('copyrightImg')
        endOfUse = request.form.get('endOfUse')
        category = request.form.get('category')
        filenames = request.files.getlist('filename')
        tagsChecked = request.form.getlist('tag')

        if isProduct == "oui" :
            isProduct = True
        else : 
            isProduct = False

        if isHuman == "oui" :
            isHuman = True
        else : 
            isHuman = False

        if isInstitutional == "oui" :
            isInstitutional = True
        else : 
            isInstitutional = False

        if rightOfUse == "oui" :
            rightOfUse = True
        else : 
            rightOfUse = False

        count_filename = 0
        for filename in filenames : 
            message_error = ""
            resp = uploadImage(filename)
            if not resp : 
                message_error = "Le type du fichier n'est pas sous le bon format"
            else :
                filenamefinal = str(filename.filename).replace(" ", "_").replace("é", "e").replace("è", "e").replace("à", "a").replace("â", "a").replace("ä", "a").replace("ê", "e").replace("ï", "i").replace("î", "i").replace("ñ", "n").replace("ô", "o").replace("ù", "u").replace(",", "_")

                for img in images :
                    if img.name == filenamefinal:
                        message_error = "cette image existe déjà dans la base de données"
                        count_filename += 1

                if message_error != "cette image existe déjà dans la base de données" :
                    formatImg = get_format_image(filenamefinal)

                    categoryImg = Category.query.filter_by(name=category).first()

                    image = Image(filenamefinal, typeImg, isProduct, isHuman, isInstitutional, formatImg , credit, rightOfUse, copyrightImg, endOfUse, categoryImg)
                    # db.session.add(image)

                    for tag in tagsChecked :
                        tagImg = Tag.query.filter_by(id=tag).first()

                        image.tags.append(tagImg)
                    db.session.add(image)
                    
                    db.session.commit()

        if len(filenames) == 1 :
            message_error = str(len(filenames) - count_filename) + " image a été ajouté et " + str(count_filename) + " existait déjà"
        else :   
            if count_filename == 1 :
                message_error = str(len(filenames) - count_filename) + " images ont été ajouté et " + str(count_filename) + " existait déjà sur les " + str(len(filenames)) + " images"
            else :  
                message_error = str(len(filenames) - count_filename) + " images ont été ajouté et " + str(count_filename) + " existaient déjà sur les " + str(len(filenames)) + " images"
        
        

    return render_template('pages/import.html', tags=tags,  message_error= message_error)




@image.route('/find', methods=['GET', 'POST'])
def findImg():
    tags = Tag.query.all()

    pagination = 1

    if request.method == 'POST':
        filename = request.form.get('filename')
        typeImg = request.form.get('typeImg')
        isProduct = request.form.get('isProduct')
        isHuman = request.form.get('isHuman')
        isInstitutional = request.form.get('isInstitutional')
        credit = request.form.get('credit')
        category = request.form.get('category')
        filenames = request.files.get('filename')
        formatImg = request.form.get('format')
        tagsChecked = request.form.getlist('tag')

        result = execute_requete_sql(filename,typeImg,isProduct,isHuman, isInstitutional, credit, formatImg, category, tagsChecked)

        images = []
        for r in result :
            images.append({'id': r[0], 'name': r[1]})

    
    else :
        images = Image.query.limit(28).all()

    return render_template('pages/find.html', tags=tags, images=images, pagination=pagination, lenImage=int((math.floor(len(images) /4))))



@image.route('/update/<int:id>', methods=['GET', 'POST'])
def updateImg(id):
    print(id)
    tags = Tag.query.all()
    image = Image.query.filter_by(id=id).first()

    tags_image = ""
    for tag in image.tags :
        tags_image += str(tag.name) + ","

    if request.method == 'POST':
        filename = request.form.get('filename')
        typeImg = request.form.get('typeImg')
        isProduct = request.form.get('isProduct')
        isHuman = request.form.get('isHuman')
        isInstitutional = request.form.get('isInstitutional')
        credit = request.form.get('credit')
        category = request.form.get('category')
        filenames = request.files.get('filename')
        formatImg = request.form.get('format')
        tagsChecked = request.form.getlist('tag')

        if isProduct == "oui" :
            isProduct = True
        else : 
            isProduct = False

        if isHuman == "oui" :
            isHuman = True
        else : 
            isHuman = False

        if isInstitutional == "oui" :
            isInstitutional = True
        else : 
            isInstitutional = False


        categoryImg = Category.query.filter_by(name=category).first()

        old_name = image.name

        image.name = filename
        image.typeImg = typeImg
        image.isProduct = isProduct
        image.isHuman = isHuman
        image.isInstitutional = isInstitutional
        image.credit = credit
        image.category = categoryImg

        
        if tagsChecked != [] :
            for tag in tagsChecked :
                tagImg = Tag.query.filter_by(id=tag).first()
                image.tags.append(tagImg)

        db.session.add(image)
        db.session.commit()

        os.rename('app/static/img/' + str(old_name), 'app/static/img/' + str(filename))
        return redirect(url_for('image.updateImg',id=id))



    return render_template('pages/update.html', tags=tags, image=image, tags_image=tags_image)


@image.route('/delete/<int:id>', methods=['GET', 'POST'])
def delete(id):
    image = Image.query.filter_by(id=id).first()
    image.tags = []
    db.session.add(image)
    db.session.commit()
    db.session.delete(image)

    os.remove('app/static/img/' + str(image.name))
    db.session.commit()

    return redirect(url_for('image.findImg'))


@image.route('/addtag', methods=['GET', 'POST'])
def addTag():
    message = ""
    if request.method == 'POST':
        tag = request.form.get('tag')
        tag = Tag(tag)
        db.session.add(tag)
        db.session.commit()
        message = "vous avez ajouté un tag"


    return render_template('pages/addtag.html', message=message)



def execute_requete_sql(filename, typeImg,isProduct,isHuman, isInstitutional, credit, formatImg, category, tagsChecked) :
    """ Fonction qui execute la requete sql pour filtrer les images

    Args :
        all [string] : les differentes colonnes en bdd
    
    Return [list]
    """
    requetes = get_requete_sql_image(typeImg,isProduct,isHuman, isInstitutional, credit, formatImg, category, tagsChecked)
    db = pymysql.connect("localhost", "root", "", "pomona")
    cursor = db.cursor()

    select = "select * from image "

    where = "where image.name LIKE '%{}%' ".format(filename)
    for requete in requetes :
        where += requete + " "

    join = ""
    if category != "" :
        join += "join category on image.category_id = category.id "
    
    if tagsChecked != [] :
        join += "join image_tag on image.id = image_tag.image_id "

    order = "order by image.name limit 28"

    sql = select + join + where + order
    print(sql)

    cursor.execute(sql)
    result = cursor.fetchall()

    return result




def get_requete_sql_image(typeImg,isProduct,isHuman, isInstitutional, credit, formatImg, category, tagsChecked):
    """ Fonction qui recupere la requete sql si les inputs sont rempli ou non

    Args :
        all [string] : les differentes colonnes en bdd
    
    Return [list]
    """
    # on stocke dans requetes tout les "and name =" si l'input n'est pas vide, si il est vide on ne veut pas filtrer par cet input
    requetes = []
    if typeImg != "" :
        requetes.append("and typeImg = '" + str(typeImg) + "'")
    
    if isProduct != "" :
        if isProduct == "oui" :
            requetes.append("and isProduct = " + str(True))
        else : 
            requetes.append("and isProduct = " + str(False))

    if isHuman != "" :
        if isHuman == "oui" :
            requetes.append("and isHuman = " + str(True))
        else : 
            requetes.append("and isHuman = " + str(False))

    if isInstitutional != "" :
        if isInstitutional == "oui" :
            requetes.append("and isInstitutional = " + str(True))
        else : 
            requetes.append("and isInstitutional = " + str(False))
    
    if credit != "" :
        requetes.append("and credit = '" + str(credit) + "'")

    if formatImg != "" :
        requetes.append("and formatImg = '" + str(formatImg) + "'")

    if category != "" :
        cat = Category.query.filter_by(name=category).first()

app/templates/pages/addtag.html
{% extends "base.html" %}
{% block title %}Pomona - PassionFroid | Tags{% endblock %}

{% block link %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
<link rel="stylesheet" href="{{ url_for('static',filename='css/alert.css') }}">
{% endblock %}


{% block body %}

{% if message != "" %}
<div class="alert">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <strong>Info </strong> {{message}}
</div>
{% endif %}

<div style="margin: 100px auto; width: 500px; ">
    <h2 style="text-align: center;">Ajouter un tag</h2>
    <br><br>
<form style="text-align: center;" class="form-inline" action="{{ url_for('image.addTag') }}" method="post">
    <div class="form-group mx-sm-3 mb-2">
    <label class="fontstyle" for="">Nom tag</label>
    <input class="form-control" type="text" name="tag" required>
</div>
    <button class="btn btn-primary mb-2" type="submit">Ajouter un tag</button>

</form>
</div>


{% endblock body %}

{% block js %}

{% endblock %}

app/templates/pages/find.html
{% extends "base.html" %}
{% block title %}Pomona - PassionFroid | Recherche
{% endblock %}

{% block link %}

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
	<link rel="stylesheet" href="{{ url_for('static',filename='css/find.css') }}">
	<link rel="stylesheet" href="{{ url_for('static',filename='css/image.css') }}">
    <style>
        #Global #gauche {
            float:left;
            width:30%;
        }
        #Global #droite {
            margin-left:30%  ; 
            margin-right: 5%;
        }
    </style>
{% endblock %}


{% block body %}


	<!-- <ul class="recherche">
		<span class="font-recherche">
			Nous avons trouvez
			{{images|length}}
			images qui correspondent a vos critères
		</span>
	</ul> -->

	<link
	class="cssdeck" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

	<!-- <form action="/find" method="post">
	    <ul class="pagination modal-1">
	        <li>
	            <a href="#" class="prev">&laquo</a>
	        </li>
	        <li>
	            {% if pagination == 1 %}
	            <a href="#" class="active">1</a>
	            {% else %}
	            <a href="#">1</a>
	            {% endif %}
	        </li>
	        <li>
	            {% if pagination == 2 %}
	            <a href="#" class="active">2</a>
	            {% else %}
	            <a href="#">2</a>
	            {% endif %}
	        </li>
	        <li>
	            {% if pagination == 3 %}
	            <a href="#" class="active">3</a>
	            {% else %}
	            <a href="#">3</a>
	            {% endif %}
	        </li>
	        <li>
	            {% if pagination == 4 %}
	            <a href="#" class="active">4</a>
	            {% else %}
	            <a href="#">4</a>
	            {% endif %}
	        </li>
	        <li>
	            {% if pagination == 5 %}
	            <a href="#" class="active">5</a>
	            {% else %}
	            <a href="#">5</a>
	            {% endif %}
	        </li>
	        <li>
	            {% if pagination == 6 %}
	            <a href="#" class="active">6</a>
	            {% else %}
	            <a href="#">6</a>
	            {% endif %}
	        </li>
	        <li>
	            {% if pagination == 7 %}
	            <a href="#" class="active">7</a>
	            {% else %}
	            <a href="#">7</a>
	            {% endif %}
	        </li>
	        <li>
	            {% if pagination == 8 %}
	            <a href="#" class="active">8</a>
	            {% else %}
	            <a href="#">8</a>
	            {% endif %}
	        </li>
	        <li>
	            {% if pagination == 9 %}
	            <a href="#" class="active">9</a>
	            {% else %}
	            <a href="#">9</a>
	            {% endif %}
	        </li>
	        <li>
	            <a href="#" class="next">&raquo;</a>
	        </li>
	    </ul>
	</form><br> -->

    <div id="Global">
        <div id="gauche"> <div class="frame">
            <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>

            <form class="form-signin" action="/find" method="post">

                <label class="fontstyle" for="">Nom image</label>
                <input class="form-styling" type="text" name="filename">

                <label class="fontstyle" for="">Type image</label>
                <select class="select form-styling" name="typeImg">
                    <option value=""></option>
                    <option value="PassionFroid">Photo PassionFroid</option>
                    <option value="fournisseur">Photo fournisseur</option>
                    <option value="logo">Logo</option>
                </select>
                <label class="fontstyle" for="">Photo avec produit</label>
                <select class="select form-styling" name="isProduct">
                    <option value=""></option>
                    <option value="oui">Oui</option>
                    <option value="non">Non</option>
                </select>
                <br>
                <label class="fontstyle" for="">Photo avec humain</label>
                <select class="select form-styling" name="isHuman">
                    <option value=""></option>
                    <option value="oui">Oui</option>
                    <option value="non">Non</option>
                </select>
                <br>
                <label class="fontstyle" for="">Photo institutionnelle</label>
                <select class="select form-styling" name="isInstitutional">
                    <option value=""></option>
                    <option value="oui">Oui</option>
                    <option value="non">Non</option>
                </select>
                <br>
                <label class="fontstyle" for="">Crédit photo</label>
                <input class="form-styling" type="text" name="credit">

                <label class="fontstyle" for="">Catégorie</label>
                <select class="form-styling" name="category">
                    <option value=""></option>
                    <option value="Produit">Produit</option>
                    <option value="Ambiance">Ambiance</option>
                </select>

                <label class="fontstyle" for="">Format d'image</label>
                <select class="form-styling" name="format">
                    <option value=""></option>
                    <option value="horizontal">Horizontal</option>
                    <option value="vertical">Vertical</option>
                </select>

                <select name="tag" class="selectpicker" multiple data-live-search="true">
                    {% for tag in tags %}
                        <option value="{{tag.id}}">{{tag.name}}</option>
                    {% endfor %}
                </select>


                <button class="btn-animate" type="submit">Rechercher une photo</button>
                <br>

            </form>
        </div></div>
        <div id="droite"> 

            {% for i in range(0, lenImage)  %}
            <div class="row">
                {% for j in range((4 * i), ((4 * i) + 4)) %}
                <div class="col-md-3 col-sm-6">
                    <div class="product-grid">
                        <div class="product-image">
                            <a href="{{ url_for('image.updateImg', id=images[j].id) }}">
                                <img class="pic-1" src="/static/img/{{images[j].name}}">
                                <img class="pic-2" src="/static/img/{{images[j].name}}">
                            </a>
                        </div>
                        <div class="product-content">
                            <h3 class="title"><a href="{{ url_for('image.updateImg', id=images[j].id) }}">{{images[j].name}}</a></h3>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <br>
            {% endfor %}
            
        </div>
     </div>


	</div>
	{% if images|length == 0 %}
		<h3>Aucun résultat n'est disponible avec ces critères</h3>
	{% endif %}

{% endblock body %}

{% block js %}{% endblock %}

app/templates/pages/import.html
{% extends "base.html" %}
{% block title %}Pomona - PassionFroid | Importation{% endblock %}

{% block link %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
<link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename='css/alert.css') }}">
{% endblock %}


{% block body %}

{% if message_error != "" %}
<div class="alert">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <strong>Info </strong> {{message_error}}
</div>
{% endif %}
<div class="frame">
<form action="/import" method="post" enctype="multipart/form-data">

    <div class="row">
        <div class="col">
            <label class="fontstyle" for="">Nom image</label>
            <input style="border-radius: 0;" class="form-control-file" type="file" name="filename" required multiple>
        </div>
        <div class="col">
            <label class="fontstyle" for="">Type image</label>
            <select class="form-control" class="select" name="typeImg">
                <option value="PassionFroid">Photo PassionFroid</option>
                <option value="fournisseur">Photo fournisseur</option>
                <option value="logo">Logo</option>
            </select>
        </div>
    </div>
    <br>

    <div class="row">
        <div class="col">
            <label class="fontstyle" for="">Photo avec produit</label>
            <select class="form-control" name="isProduct">
                <option value="oui">Oui</option>
                <option value="non">Non</option>
            </select>
        </div>
        <div class="col">
            <label class="fontstyle" for="">Photo avec humain</label>
            <select class="form-control" name="isHuman">
                <option value="oui">Oui</option>
                <option value="non">Non</option>
            </select>
            </select>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col">
            <label class="fontstyle" for="">Photo institutionnelle</label>
            <select class="form-control" name="isInstitutional">
                <option value="oui">Oui</option>
                <option value="non">Non</option>
            </select>
        </div>
        <div class="col">
            <label class="fontstyle" for="">Crédit photo</label>
            <input class="form-control" type="text" name="credit" required>
        </div>
    </div>
    <br>

    <div class="row">
        <div class="col">
            <label class="fontstyle" for="">Droits d'utilisation limités</label>
            <select class="rightOfUse-js form-control" name="rightOfUse">
                <option value="oui">Oui</option>
                <option value="non">Non</option>
            </select>
        </div>
        <div class="col">
            <div class="isVisible-js">
                <label class="fontstyle" for="">Copyright</label>
                <input class="form-control" type="text" name="copyrightImg" required>
            </div>
        </div>
    </div>
    <br>


    <div class="row">
        <div class="col">
            <label class="fontstyle" for="">Catégorie</label>
            <select class="form-control" name="category">
                <option value="Produit">Produit</option>
                <option value="Ambiance">Ambiance</option>
            </select>
        </div>
        <div class="col">
            <div class="isVisible-js">
                <label class="fontstyle" for="">Date de fin de droits d’utilisation</label>
                <input class="form-control" type="date" name="endOfUse" required>
            </div>
        </div>
    </div>
    <br>

<div class="form-group">
    <label class="fontstyle" for="">Tag</label>
    <select name="tag" class="selectpicker" multiple data-live-search="true">
        {% for tag in tags %}
        <option value="{{tag.id}}">{{tag.name}}</option>
        {% endfor %}
    </select>
</div>

    <button type="submit" class="btn btn-primary">Importer une photo</button>

</form>
</div>

{% endblock body %}

{% block js %}

{% endblock %}

app/templates/pages/update.html
{% extends "base.html" %}
{% block title %}Pomona - PassionFroid | Modification{% endblock %}

{% block link %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
<link rel="stylesheet" href="{{ url_for('static',filename='css/update.css') }}">
{% endblock %}


{% block body %}


<!-- Display image to edit -->
<div class="preview">
    <a href="/static/img/{{image.name}}" download>
        <img src="/static/img/{{image.name}}">
        <p style="text-align: center;">Télécharger la photo</p>
    </a>
</div>

<div class="frame"></div>
<form action="{{ url_for('image.updateImg', id=image.id ) }}" method="post">

    <div class="row">
        <div class="col">
            <label class="fontstyle" for="">Nom image</label>
            <input type="text" name="filename" value="{{image.name}}">
        </div>
        <div class="col">
            <label class="fontstyle" for="">Type image</label>
            <select class="select" name="typeImg">
                {% if image.typeImg == "PassionFroid" %}
                <option selected value="PassionFroid">Photo PassionFroid</option>
                <option value="fournisseur">Photo fournisseur</option>
                <option value="logo">Logo</option>
                {% elif image.typeImg == "fournisseur" %}
                <option value="PassionFroid">Photo PassionFroid</option>
                <option selected value="fournisseur">Photo fournisseur</option>
                <option value="logo">Logo</option>
                {% else %}
                <option value="PassionFroid">Photo PassionFroid</option>
                <option value="fournisseur">Photo fournisseur</option>
                <option selected value="logo">Logo</option>
                {% endif %}
            </select>
        </div>
        <div class="col">
            <label class="fontstyle" for="">Photo avec produit</label>
            <select class="select" name="isProduct">
                {% if image.isProduct == True %}
                <option selected value="oui">Oui</option>
                <option value="non">Non</option>
                {% else %}
                <option value="oui">Oui</option>
                <option selected value="non">Non</option>
                {% endif %}
            </select>
        </div>
    </div>

    <br>

    <div class="row">
        <div class="col">
            <label class="fontstyle" for="">Photo avec humain</label>
            <select class="select" name="isHuman">
                {% if image.isHuman == True %}
                <option selected value="oui">Oui</option>
                <option value="non">Non</option>
                {% else %}
                <option value="oui">Oui</option>
                <option selected value="non">Non</option>
                {% endif %}
            </select>
        </div>
        <div class="col">
            <label class="fontstyle" for="">Photo institutionnelle</label>
            <select class="select" name="isInstitutional">
                {% if image.isInstitutional == True %}
                <option selected value="oui">Oui</option>
                <option value="non">Non</option>
                {% else %}
                <option value="oui">Oui</option>
                <option selected value="non">Non</option>
                {% endif %}
            </select>
        </div>
        <div class="col">
            <label class="fontstyle" for="">Crédit photo</label>
            <input type="text" name="credit" value="{{image.credit}}">
        </div>
    </div>

    <br>
    
    <div class="row">
        <div class="col">
            <label class="fontstyle" for="">Catégorie</label>
            <select name="category">
                {% if image.category_id == 1 %}
                <option selected value="Produit">Produit</option>
                <option value="Ambiance">Ambiance</option>
                {% else %}
                <option value="Produit">Produit</option>
                <option selected value="Ambiance">Ambiance</option>
                {% endif %}
            </select>
        </div>
        <div class="col">
            <label class="fontstyle" for="">Tags</label>
            <select name="tag" class="selectpicker" multiple data-live-search="true">
                {% for tag in tags %}
                <option value="{{tag.id}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <br>

    <input type="hidden" name="" class="hidden" value="{{tags_image}}">


    <button type="submit">Modifier la photo</button>
</form>
</div>
<br>
<a href="{{ url_for('image.delete', id=image.id ) }}"><button> Supprimer la photo</button></a>

{% endblock body %}

{% block js %}
<script src="{{ url_for('static',filename='js/tag.js') }}"></script>
{% endblock %}